#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
#include <bits/stdc++.h>
using namespace std;



// Generated by 2.9.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    int N;
    cin >> N;
    vector<long double> x(N);
    vector<long double> y(N);
    for(int i=0;i<N;i++){
        cin >>x[i]>>y[i];
    }

    long double maxd=0;
    for(int i=0;i<N;i++){
        for(int j=i+1;j<N;j++){
            if (maxd <(x[i]-x[j])*(x[i]-x[j])+(y[i]-y[j])*(y[i]-y[j]))
                maxd = (x[i]-x[j])*(x[i]-x[j])+(y[i]-y[j])*(y[i]-y[j]);
        }
    }
    cout << fixed << setprecision(10) <<sqrtl((long double)maxd)<<endl;
    // Failed to predict input format
    return 0;
}
