#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;



// Generated by 2.9.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N,X;
    cin >>N>>X;
    vector<vector<long long>> A(N);
    vector<long long> L(N);
    long long Ai;
    for (int i=0;i<N;i++){
        cin >> l[i];
        for (int j=0; j<L[i]; j++) {
            cin >> Ai;
            A[i].push_back(Ai);
        }
    }
    queue<long long> q;
    q.push(X);
    long long cnt = 1;
    long long cnt2;
    long long bal;
    for (long long i=0; i<N; i++) {
        cnt2 = 0;
        for (int j=0; j<cnt; j+)f
            bal = que.front();
            for (int m=0; m<l[k]; mtt) (
                if (ball&a[k] [m]==0) (
                    que.push (ball/a [k] [m] );
                    cnt2++;
            que.pop();
        cnt = cnt2;
    int ans = 0;
    while(!que.empty())[
        int num = que.front();
        if (num==1) ans+t;
        que.pop();
    cout << ans << endl;
    // Failed to predict input format
    return 0;
}
