#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;


void solve(long long k, long long n, long long m, std::vector<std::string> a, std::vector<std::string> b){

}

// Generated by 2.9.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long k;
    std::scanf("%lld", &k);
    long long n;
    std::scanf("%lld", &n);
    long long m;
    std::scanf("%lld", &m);
    std::vector<std::string> a(n);
    for(int i = 0 ; i < n ; i++){
        std::cin >> a[i];
    }
    std::vector<std::string> b(m);
    for(int i = 0 ; i < m ; i++){
        std::cin >> b[i];
    }
    solve(k, n, m, std::move(a), std::move(b));
    return 0;
}
