#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;



// Generated by 2.9.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    string S;
    cin >> S;

    int L = S.length();
    long long cnt = 0;

    for(int i=0;S[i];i++){
        if(S[i]=='U')
            cnt += (L-i-1) + (i)*2;
        else
            cnt += (L-i-1)*2 + i;
    }

    cout << cnt <<endl;

    return 0;
}
