#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;


void solve(long long N, std::vector<long long> a){
    vector<long long> S(N+1,0);
    int cnt = 0;
    for(int i=0;i<N;i++)
        S[i+1]=a[i]+S[i];
    if(S[N]%N)
        cout<<-1<<endl;
    else{
        for(int i=0;i<N;i++)
            if(S[i+1]/(i+1)!=S[N]/N)
                cnt++;
        cout<<cnt<<endl;
    }
}

// Generated by 2.9.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    std::scanf("%lld", &N);
    std::vector<long long> a(N);
    for(int i = 0 ; i < N ; i++){
        std::scanf("%lld", &a[i]);
    }
    solve(N, std::move(a));
    return 0;
}
