#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;


void solve(long long N){
    long long ans2 = N;
    for(long long i=2;i*i<=N;i++){
        ans2 += N/i - (i-1);
    }

    for(long long i=2;i*i*i<=N;i++){
        ans2 += N/i/i - (i-1);
    }
    long long j=3;
    for(long long i=2;i*i*i<=N;i++){
        for(j=i+1;i*j*j<=N;j++){
            ans2+= N/i/j - (j-1);
        }
    }
    cout << ans2 <<endl;
    //cout <<ans <<endl;
}

// Generated by 2.9.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    std::scanf("%lld", &N);
    solve(N);
    return 0;
}
