#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;


void solve(long long N, long long K, std::vector<long long> P){
    set<long long> s;
    for(int i=0;i<K-1;i++)
        s.insert(P[i]);

    set<long long>::iterator it=s.begin();
   
    for(int i=0;i<N-K+1;i++){
        s.insert(P[K-1+i]);
        cout<<*it<<endl;
        if(P[K+i]>*it)
            it++;
    }

}

// Generated by 2.9.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    std::scanf("%lld", &N);
    long long K;
    std::scanf("%lld", &K);
    std::vector<long long> P(N);
    for(int i = 0 ; i < N ; i++){
        std::scanf("%lld", &P[i]);
    }
    solve(N, K, std::move(P));
    return 0;
}
