#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;


void solve(long long K){
    vector<char> c;
    for(int i=0;K>>i;i++){
        if ((K>>i)&1)
            c.push_back('2');
        else
            c.push_back('0');
    }
    reverse(c.begin(),c.end());
    c.push_back(0);

    for(int i=0;c[i];i++)
        cout<<c[i];
    cout<<endl;
}

// Generated by 2.9.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long K;
    std::scanf("%lld", &K);
    solve(K);
    return 0;
}
