#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;


void solve(long long L, long long R, std::vector<long long> A, std::vector<long long> B, std::vector<std::vector<long long>> C){

}

// Generated by 2.9.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long L;
    std::scanf("%lld", &L);
    long long R;
    std::scanf("%lld", &R);
    std::vector<long long> A(L);
    for(int i = 0 ; i < L ; i++){
        std::scanf("%lld", &A[i]);
    }
    std::vector<long long> B(R);
    for(int i = 0 ; i < R ; i++){
        std::scanf("%lld", &B[i]);
    }
    std::vector<std::vector<long long>> C(L, std::vector<long long>(R));
    for(int i = 0 ; i < L ; i++){
        for(int j = 0 ; j < R ; j++){
            std::scanf("%lld", &C[i][j]);
        }
    }
    solve(L, R, std::move(A), std::move(B), std::move(C));
    return 0;
}
